// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: Common.proto

package netproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PlatformCommonClassID int32

const (
	PlatformCommonClassID_TipMessageID             PlatformCommonClassID = 1
	PlatformCommonClassID_HeartBeatID              PlatformCommonClassID = 2
	PlatformCommonClassID_HeartBeatReturnID        PlatformCommonClassID = 3
	PlatformCommonClassID_RequestHeartBeatConfigID PlatformCommonClassID = 4
	PlatformCommonClassID_HeartBeatConfigID        PlatformCommonClassID = 5
	PlatformCommonClassID_IPReportID               PlatformCommonClassID = 6
	PlatformCommonClassID_ConnTokenID              PlatformCommonClassID = 7
	PlatformCommonClassID_RefreshToken             PlatformCommonClassID = 12 //刷新user token
	PlatformCommonClassID_RefreshTokenRet          PlatformCommonClassID = 13 //返回刷新user token
)

// Enum value maps for PlatformCommonClassID.
var (
	PlatformCommonClassID_name = map[int32]string{
		1:  "TipMessageID",
		2:  "HeartBeatID",
		3:  "HeartBeatReturnID",
		4:  "RequestHeartBeatConfigID",
		5:  "HeartBeatConfigID",
		6:  "IPReportID",
		7:  "ConnTokenID",
		12: "RefreshToken",
		13: "RefreshTokenRet",
	}
	PlatformCommonClassID_value = map[string]int32{
		"TipMessageID":             1,
		"HeartBeatID":              2,
		"HeartBeatReturnID":        3,
		"RequestHeartBeatConfigID": 4,
		"HeartBeatConfigID":        5,
		"IPReportID":               6,
		"ConnTokenID":              7,
		"RefreshToken":             12,
		"RefreshTokenRet":          13,
	}
)

func (x PlatformCommonClassID) Enum() *PlatformCommonClassID {
	p := new(PlatformCommonClassID)
	*p = x
	return p
}

func (x PlatformCommonClassID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformCommonClassID) Descriptor() protoreflect.EnumDescriptor {
	return file_Common_proto_enumTypes[0].Descriptor()
}

func (PlatformCommonClassID) Type() protoreflect.EnumType {
	return &file_Common_proto_enumTypes[0]
}

func (x PlatformCommonClassID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PlatformCommonClassID) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PlatformCommonClassID(num)
	return nil
}

// Deprecated: Use PlatformCommonClassID.Descriptor instead.
func (PlatformCommonClassID) EnumDescriptor() ([]byte, []int) {
	return file_Common_proto_rawDescGZIP(), []int{0}
}

var File_Common_proto protoreflect.FileDescriptor

var file_Common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xce, 0x01, 0x0a, 0x15, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x49, 0x44, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x69, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x49, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61,
	0x74, 0x49, 0x44, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65,
	0x61, 0x74, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x49, 0x44, 0x10, 0x03, 0x12, 0x1c, 0x0a, 0x18,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x10, 0x04, 0x12, 0x15, 0x0a, 0x11, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x44, 0x10,
	0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x50, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x44, 0x10,
	0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x44,
	0x10, 0x07, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x10, 0x0c, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x74, 0x10, 0x0d, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6e,
	0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_Common_proto_rawDescOnce sync.Once
	file_Common_proto_rawDescData = file_Common_proto_rawDesc
)

func file_Common_proto_rawDescGZIP() []byte {
	file_Common_proto_rawDescOnce.Do(func() {
		file_Common_proto_rawDescData = protoimpl.X.CompressGZIP(file_Common_proto_rawDescData)
	})
	return file_Common_proto_rawDescData
}

var file_Common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Common_proto_goTypes = []interface{}{
	(PlatformCommonClassID)(0), // 0: netproto.PlatformCommonClassID
}
var file_Common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Common_proto_init() }
func file_Common_proto_init() {
	if File_Common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Common_proto_goTypes,
		DependencyIndexes: file_Common_proto_depIdxs,
		EnumInfos:         file_Common_proto_enumTypes,
	}.Build()
	File_Common_proto = out.File
	file_Common_proto_rawDesc = nil
	file_Common_proto_goTypes = nil
	file_Common_proto_depIdxs = nil
}
