// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: Game_HBSL.proto

package netproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HBSL_GameMessageClassID int32

const (
	HBSL_GameMessageClassID_HBSLSettingID         HBSL_GameMessageClassID = 10001 //设置相关 S2C
	HBSL_GameMessageClassID_HBSLStateID           HBSL_GameMessageClassID = 10002 //阶段ID S2C
	HBSL_GameMessageClassID_HBSLFaHongbaoID       HBSL_GameMessageClassID = 10003 //发红包 C2S
	HBSL_GameMessageClassID_HBSLFaHongbaoRetID    HBSL_GameMessageClassID = 10004 //发红包结果 S2C
	HBSL_GameMessageClassID_HBSLZhuangInfoID      HBSL_GameMessageClassID = 10005 //庄家信息 S2C
	HBSL_GameMessageClassID_HBSLQiangHongbaoID    HBSL_GameMessageClassID = 10006 //用户抢红包 C2S
	HBSL_GameMessageClassID_HBSLQiangHongbaoRetID HBSL_GameMessageClassID = 10007 //用户抢红包结果 S2C
	HBSL_GameMessageClassID_HBSLLastGameResultID  HBSL_GameMessageClassID = 10008 //上次开奖结果s2c，在用户进入时发送
	HBSL_GameMessageClassID_HBSLZhuangWinResultID HBSL_GameMessageClassID = 10009 //广播庄家赢钱结果 S2C, HBSL_ZhuangWin
	HBSL_GameMessageClassID_HBSLHongbaoListID     HBSL_GameMessageClassID = 10010 //请求待抢红包列表 c2s,
	HBSL_GameMessageClassID_HBSLHongbaoListRetID  HBSL_GameMessageClassID = 10011 ////请求待抢红包列表 s2c, HBSL_HongbaoList
)

// Enum value maps for HBSL_GameMessageClassID.
var (
	HBSL_GameMessageClassID_name = map[int32]string{
		10001: "HBSLSettingID",
		10002: "HBSLStateID",
		10003: "HBSLFaHongbaoID",
		10004: "HBSLFaHongbaoRetID",
		10005: "HBSLZhuangInfoID",
		10006: "HBSLQiangHongbaoID",
		10007: "HBSLQiangHongbaoRetID",
		10008: "HBSLLastGameResultID",
		10009: "HBSLZhuangWinResultID",
		10010: "HBSLHongbaoListID",
		10011: "HBSLHongbaoListRetID",
	}
	HBSL_GameMessageClassID_value = map[string]int32{
		"HBSLSettingID":         10001,
		"HBSLStateID":           10002,
		"HBSLFaHongbaoID":       10003,
		"HBSLFaHongbaoRetID":    10004,
		"HBSLZhuangInfoID":      10005,
		"HBSLQiangHongbaoID":    10006,
		"HBSLQiangHongbaoRetID": 10007,
		"HBSLLastGameResultID":  10008,
		"HBSLZhuangWinResultID": 10009,
		"HBSLHongbaoListID":     10010,
		"HBSLHongbaoListRetID":  10011,
	}
)

func (x HBSL_GameMessageClassID) Enum() *HBSL_GameMessageClassID {
	p := new(HBSL_GameMessageClassID)
	*p = x
	return p
}

func (x HBSL_GameMessageClassID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HBSL_GameMessageClassID) Descriptor() protoreflect.EnumDescriptor {
	return file_Game_HBSL_proto_enumTypes[0].Descriptor()
}

func (HBSL_GameMessageClassID) Type() protoreflect.EnumType {
	return &file_Game_HBSL_proto_enumTypes[0]
}

func (x HBSL_GameMessageClassID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HBSL_GameMessageClassID) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HBSL_GameMessageClassID(num)
	return nil
}

// Deprecated: Use HBSL_GameMessageClassID.Descriptor instead.
func (HBSL_GameMessageClassID) EnumDescriptor() ([]byte, []int) {
	return file_Game_HBSL_proto_rawDescGZIP(), []int{0}
}

var File_Game_HBSL_proto protoreflect.FileDescriptor

var file_Game_HBSL_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x5f, 0x48, 0x42, 0x53, 0x4c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xa4, 0x02, 0x0a, 0x17,
	0x48, 0x42, 0x53, 0x4c, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x0d, 0x48, 0x42, 0x53, 0x4c, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x44, 0x10, 0x91, 0x4e, 0x12, 0x10, 0x0a, 0x0b, 0x48,
	0x42, 0x53, 0x4c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x49, 0x44, 0x10, 0x92, 0x4e, 0x12, 0x14, 0x0a,
	0x0f, 0x48, 0x42, 0x53, 0x4c, 0x46, 0x61, 0x48, 0x6f, 0x6e, 0x67, 0x62, 0x61, 0x6f, 0x49, 0x44,
	0x10, 0x93, 0x4e, 0x12, 0x17, 0x0a, 0x12, 0x48, 0x42, 0x53, 0x4c, 0x46, 0x61, 0x48, 0x6f, 0x6e,
	0x67, 0x62, 0x61, 0x6f, 0x52, 0x65, 0x74, 0x49, 0x44, 0x10, 0x94, 0x4e, 0x12, 0x15, 0x0a, 0x10,
	0x48, 0x42, 0x53, 0x4c, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x44,
	0x10, 0x95, 0x4e, 0x12, 0x17, 0x0a, 0x12, 0x48, 0x42, 0x53, 0x4c, 0x51, 0x69, 0x61, 0x6e, 0x67,
	0x48, 0x6f, 0x6e, 0x67, 0x62, 0x61, 0x6f, 0x49, 0x44, 0x10, 0x96, 0x4e, 0x12, 0x1a, 0x0a, 0x15,
	0x48, 0x42, 0x53, 0x4c, 0x51, 0x69, 0x61, 0x6e, 0x67, 0x48, 0x6f, 0x6e, 0x67, 0x62, 0x61, 0x6f,
	0x52, 0x65, 0x74, 0x49, 0x44, 0x10, 0x97, 0x4e, 0x12, 0x19, 0x0a, 0x14, 0x48, 0x42, 0x53, 0x4c,
	0x4c, 0x61, 0x73, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x44,
	0x10, 0x98, 0x4e, 0x12, 0x1a, 0x0a, 0x15, 0x48, 0x42, 0x53, 0x4c, 0x5a, 0x68, 0x75, 0x61, 0x6e,
	0x67, 0x57, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x44, 0x10, 0x99, 0x4e, 0x12,
	0x16, 0x0a, 0x11, 0x48, 0x42, 0x53, 0x4c, 0x48, 0x6f, 0x6e, 0x67, 0x62, 0x61, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x49, 0x44, 0x10, 0x9a, 0x4e, 0x12, 0x19, 0x0a, 0x14, 0x48, 0x42, 0x53, 0x4c, 0x48,
	0x6f, 0x6e, 0x67, 0x62, 0x61, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x74, 0x49, 0x44, 0x10,
	0x9b, 0x4e, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_Game_HBSL_proto_rawDescOnce sync.Once
	file_Game_HBSL_proto_rawDescData = file_Game_HBSL_proto_rawDesc
)

func file_Game_HBSL_proto_rawDescGZIP() []byte {
	file_Game_HBSL_proto_rawDescOnce.Do(func() {
		file_Game_HBSL_proto_rawDescData = protoimpl.X.CompressGZIP(file_Game_HBSL_proto_rawDescData)
	})
	return file_Game_HBSL_proto_rawDescData
}

var file_Game_HBSL_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Game_HBSL_proto_goTypes = []interface{}{
	(HBSL_GameMessageClassID)(0), // 0: netproto.HBSL_GameMessageClassID
}
var file_Game_HBSL_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Game_HBSL_proto_init() }
func file_Game_HBSL_proto_init() {
	if File_Game_HBSL_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Game_HBSL_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Game_HBSL_proto_goTypes,
		DependencyIndexes: file_Game_HBSL_proto_depIdxs,
		EnumInfos:         file_Game_HBSL_proto_enumTypes,
	}.Build()
	File_Game_HBSL_proto = out.File
	file_Game_HBSL_proto_rawDesc = nil
	file_Game_HBSL_proto_goTypes = nil
	file_Game_HBSL_proto_depIdxs = nil
}
