// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: GameMsg_QZNN.proto

package netproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type QZNN_GameStep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Step *int32 `protobuf:"varint,1,req,name=Step" json:"Step,omitempty"` //流程
	Time *int32 `protobuf:"varint,2,req,name=Time" json:"Time,omitempty"` //時間秒
}

func (x *QZNN_GameStep) Reset() {
	*x = QZNN_GameStep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_GameStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_GameStep) ProtoMessage() {}

func (x *QZNN_GameStep) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_GameStep.ProtoReflect.Descriptor instead.
func (*QZNN_GameStep) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{0}
}

func (x *QZNN_GameStep) GetStep() int32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

func (x *QZNN_GameStep) GetTime() int32 {
	if x != nil && x.Time != nil {
		return *x.Time
	}
	return 0
}

type QZNN_QiangZhuang struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *int32 `protobuf:"varint,1,req,name=Times" json:"Times,omitempty"`
}

func (x *QZNN_QiangZhuang) Reset() {
	*x = QZNN_QiangZhuang{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_QiangZhuang) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_QiangZhuang) ProtoMessage() {}

func (x *QZNN_QiangZhuang) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_QiangZhuang.ProtoReflect.Descriptor instead.
func (*QZNN_QiangZhuang) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{1}
}

func (x *QZNN_QiangZhuang) GetTimes() int32 {
	if x != nil && x.Times != nil {
		return *x.Times
	}
	return 0
}

type QZNN_ConfirmZhuang struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZhuangUserID *int32          `protobuf:"varint,1,opt,name=ZhuangUserID" json:"ZhuangUserID,omitempty"`
	Times        *int32          `protobuf:"varint,2,opt,name=Times" json:"Times,omitempty"` //押注倍數 or 金額
	UserBets     []*QZNN_UserBet `protobuf:"bytes,3,rep,name=UserBets" json:"UserBets,omitempty"`
}

func (x *QZNN_ConfirmZhuang) Reset() {
	*x = QZNN_ConfirmZhuang{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_ConfirmZhuang) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_ConfirmZhuang) ProtoMessage() {}

func (x *QZNN_ConfirmZhuang) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_ConfirmZhuang.ProtoReflect.Descriptor instead.
func (*QZNN_ConfirmZhuang) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{2}
}

func (x *QZNN_ConfirmZhuang) GetZhuangUserID() int32 {
	if x != nil && x.ZhuangUserID != nil {
		return *x.ZhuangUserID
	}
	return 0
}

func (x *QZNN_ConfirmZhuang) GetTimes() int32 {
	if x != nil && x.Times != nil {
		return *x.Times
	}
	return 0
}

func (x *QZNN_ConfirmZhuang) GetUserBets() []*QZNN_UserBet {
	if x != nil {
		return x.UserBets
	}
	return nil
}

type QZNN_UserBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID    *int32 `protobuf:"varint,1,req,name=UserID" json:"UserID,omitempty"`
	Times     *int64 `protobuf:"varint,2,req,name=Times" json:"Times,omitempty"`
	SystemSet *bool  `protobuf:"varint,3,req,name=SystemSet" json:"SystemSet,omitempty"`
}

func (x *QZNN_UserBet) Reset() {
	*x = QZNN_UserBet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_UserBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_UserBet) ProtoMessage() {}

func (x *QZNN_UserBet) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_UserBet.ProtoReflect.Descriptor instead.
func (*QZNN_UserBet) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{3}
}

func (x *QZNN_UserBet) GetUserID() int32 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

func (x *QZNN_UserBet) GetTimes() int64 {
	if x != nil && x.Times != nil {
		return *x.Times
	}
	return 0
}

func (x *QZNN_UserBet) GetSystemSet() bool {
	if x != nil && x.SystemSet != nil {
		return *x.SystemSet
	}
	return false
}

type QZNN_XianJiaBetTimes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *int64 `protobuf:"varint,1,req,name=Times" json:"Times,omitempty"` //閑家倍數 or 閑家下注金額
}

func (x *QZNN_XianJiaBetTimes) Reset() {
	*x = QZNN_XianJiaBetTimes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_XianJiaBetTimes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_XianJiaBetTimes) ProtoMessage() {}

func (x *QZNN_XianJiaBetTimes) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_XianJiaBetTimes.ProtoReflect.Descriptor instead.
func (*QZNN_XianJiaBetTimes) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{4}
}

func (x *QZNN_XianJiaBetTimes) GetTimes() int64 {
	if x != nil && x.Times != nil {
		return *x.Times
	}
	return 0
}

type QZNN_NotifyXianJiaBetTimes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserBets []*QZNN_UserBet `protobuf:"bytes,1,rep,name=UserBets" json:"UserBets,omitempty"`
}

func (x *QZNN_NotifyXianJiaBetTimes) Reset() {
	*x = QZNN_NotifyXianJiaBetTimes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_NotifyXianJiaBetTimes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_NotifyXianJiaBetTimes) ProtoMessage() {}

func (x *QZNN_NotifyXianJiaBetTimes) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_NotifyXianJiaBetTimes.ProtoReflect.Descriptor instead.
func (*QZNN_NotifyXianJiaBetTimes) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{5}
}

func (x *QZNN_NotifyXianJiaBetTimes) GetUserBets() []*QZNN_UserBet {
	if x != nil {
		return x.UserBets
	}
	return nil
}

type QZNN_LastPokerCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card *PokerCard `protobuf:"bytes,1,req,name=Card" json:"Card,omitempty"`
}

func (x *QZNN_LastPokerCard) Reset() {
	*x = QZNN_LastPokerCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_LastPokerCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_LastPokerCard) ProtoMessage() {}

func (x *QZNN_LastPokerCard) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_LastPokerCard.ProtoReflect.Descriptor instead.
func (*QZNN_LastPokerCard) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{6}
}

func (x *QZNN_LastPokerCard) GetCard() *PokerCard {
	if x != nil {
		return x.Card
	}
	return nil
}

type QZNN_UserCardGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardsThree []*PokerCard `protobuf:"bytes,1,rep,name=CardsThree" json:"CardsThree,omitempty"`
	CardsTwo   []*PokerCard `protobuf:"bytes,2,rep,name=CardsTwo" json:"CardsTwo,omitempty"`
}

func (x *QZNN_UserCardGroup) Reset() {
	*x = QZNN_UserCardGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_UserCardGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_UserCardGroup) ProtoMessage() {}

func (x *QZNN_UserCardGroup) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_UserCardGroup.ProtoReflect.Descriptor instead.
func (*QZNN_UserCardGroup) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{7}
}

func (x *QZNN_UserCardGroup) GetCardsThree() []*PokerCard {
	if x != nil {
		return x.CardsThree
	}
	return nil
}

func (x *QZNN_UserCardGroup) GetCardsTwo() []*PokerCard {
	if x != nil {
		return x.CardsTwo
	}
	return nil
}

type QZNN_GameRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZhuangRet *QZNN_UserRet   `protobuf:"bytes,1,req,name=ZhuangRet" json:"ZhuangRet,omitempty"`
	UserRet   []*QZNN_UserRet `protobuf:"bytes,2,rep,name=UserRet" json:"UserRet,omitempty"`
}

func (x *QZNN_GameRet) Reset() {
	*x = QZNN_GameRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_GameRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_GameRet) ProtoMessage() {}

func (x *QZNN_GameRet) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_GameRet.ProtoReflect.Descriptor instead.
func (*QZNN_GameRet) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{8}
}

func (x *QZNN_GameRet) GetZhuangRet() *QZNN_UserRet {
	if x != nil {
		return x.ZhuangRet
	}
	return nil
}

func (x *QZNN_GameRet) GetUserRet() []*QZNN_UserRet {
	if x != nil {
		return x.UserRet
	}
	return nil
}

type QZNN_UserRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User            *GameUser    `protobuf:"bytes,1,req,name=User" json:"User,omitempty"`
	WinLose         *int64       `protobuf:"varint,2,req,name=WinLose" json:"WinLose,omitempty"`
	NiuNiuRet       *int32       `protobuf:"varint,3,req,name=NiuNiuRet" json:"NiuNiuRet,omitempty"`
	NiuNiuRetNumber *int32       `protobuf:"varint,4,req,name=NiuNiuRetNumber" json:"NiuNiuRetNumber,omitempty"`
	NiuNiuBetTimes  *int32       `protobuf:"varint,5,req,name=NiuNiuBetTimes" json:"NiuNiuBetTimes,omitempty"`
	CardGroup       []*PokerCard `protobuf:"bytes,6,rep,name=CardGroup" json:"CardGroup,omitempty"`
	JackpotBonus    *int64       `protobuf:"varint,7,opt,name=JackpotBonus" json:"JackpotBonus,omitempty"`
}

func (x *QZNN_UserRet) Reset() {
	*x = QZNN_UserRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_UserRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_UserRet) ProtoMessage() {}

func (x *QZNN_UserRet) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_UserRet.ProtoReflect.Descriptor instead.
func (*QZNN_UserRet) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{9}
}

func (x *QZNN_UserRet) GetUser() *GameUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *QZNN_UserRet) GetWinLose() int64 {
	if x != nil && x.WinLose != nil {
		return *x.WinLose
	}
	return 0
}

func (x *QZNN_UserRet) GetNiuNiuRet() int32 {
	if x != nil && x.NiuNiuRet != nil {
		return *x.NiuNiuRet
	}
	return 0
}

func (x *QZNN_UserRet) GetNiuNiuRetNumber() int32 {
	if x != nil && x.NiuNiuRetNumber != nil {
		return *x.NiuNiuRetNumber
	}
	return 0
}

func (x *QZNN_UserRet) GetNiuNiuBetTimes() int32 {
	if x != nil && x.NiuNiuBetTimes != nil {
		return *x.NiuNiuBetTimes
	}
	return 0
}

func (x *QZNN_UserRet) GetCardGroup() []*PokerCard {
	if x != nil {
		return x.CardGroup
	}
	return nil
}

func (x *QZNN_UserRet) GetJackpotBonus() int64 {
	if x != nil && x.JackpotBonus != nil {
		return *x.JackpotBonus
	}
	return 0
}

type QZNN_GameSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZhuangBetTimes     []int32 `protobuf:"varint,1,rep,name=ZhuangBetTimes" json:"ZhuangBetTimes,omitempty"`
	XianBetTimes       []int32 `protobuf:"varint,2,rep,name=XianBetTimes" json:"XianBetTimes,omitempty"`
	QiangZhuangTimeout *int32  `protobuf:"varint,3,req,name=QiangZhuangTimeout" json:"QiangZhuangTimeout,omitempty"`
	XianBetTimeout     *int32  `protobuf:"varint,4,req,name=XianBetTimeout" json:"XianBetTimeout,omitempty"`
	CardGroupTimeout   *int32  `protobuf:"varint,5,req,name=CardGroupTimeout" json:"CardGroupTimeout,omitempty"`
	BaseScore          *int32  `protobuf:"varint,6,req,name=BaseScore" json:"BaseScore,omitempty"`
	TableNo            *int32  `protobuf:"varint,7,req,name=TableNo" json:"TableNo,omitempty"`
	GameID             *int32  `protobuf:"varint,8,req,name=GameID" json:"GameID,omitempty"`
	ReadyTimeout       *int32  `protobuf:"varint,9,req,name=ReadyTimeout" json:"ReadyTimeout,omitempty"`
}

func (x *QZNN_GameSetting) Reset() {
	*x = QZNN_GameSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_GameSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_GameSetting) ProtoMessage() {}

func (x *QZNN_GameSetting) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_GameSetting.ProtoReflect.Descriptor instead.
func (*QZNN_GameSetting) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{10}
}

func (x *QZNN_GameSetting) GetZhuangBetTimes() []int32 {
	if x != nil {
		return x.ZhuangBetTimes
	}
	return nil
}

func (x *QZNN_GameSetting) GetXianBetTimes() []int32 {
	if x != nil {
		return x.XianBetTimes
	}
	return nil
}

func (x *QZNN_GameSetting) GetQiangZhuangTimeout() int32 {
	if x != nil && x.QiangZhuangTimeout != nil {
		return *x.QiangZhuangTimeout
	}
	return 0
}

func (x *QZNN_GameSetting) GetXianBetTimeout() int32 {
	if x != nil && x.XianBetTimeout != nil {
		return *x.XianBetTimeout
	}
	return 0
}

func (x *QZNN_GameSetting) GetCardGroupTimeout() int32 {
	if x != nil && x.CardGroupTimeout != nil {
		return *x.CardGroupTimeout
	}
	return 0
}

func (x *QZNN_GameSetting) GetBaseScore() int32 {
	if x != nil && x.BaseScore != nil {
		return *x.BaseScore
	}
	return 0
}

func (x *QZNN_GameSetting) GetTableNo() int32 {
	if x != nil && x.TableNo != nil {
		return *x.TableNo
	}
	return 0
}

func (x *QZNN_GameSetting) GetGameID() int32 {
	if x != nil && x.GameID != nil {
		return *x.GameID
	}
	return 0
}

func (x *QZNN_GameSetting) GetReadyTimeout() int32 {
	if x != nil && x.ReadyTimeout != nil {
		return *x.ReadyTimeout
	}
	return 0
}

type QZNN_GameScene struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStep           *int32                      `protobuf:"varint,1,req,name=GameStep" json:"GameStep,omitempty"`
	UserPoker          *UserPoker                  `protobuf:"bytes,2,opt,name=UserPoker" json:"UserPoker,omitempty"`
	ZhuangInfo         *QZNN_ConfirmZhuang         `protobuf:"bytes,3,opt,name=ZhuangInfo" json:"ZhuangInfo,omitempty"`
	XianInfo           *QZNN_NotifyXianJiaBetTimes `protobuf:"bytes,4,opt,name=XianInfo" json:"XianInfo,omitempty"`
	ElapsedSeconds     *int32                      `protobuf:"varint,5,opt,name=ElapsedSeconds" json:"ElapsedSeconds,omitempty"`
	GameRet            *QZNN_GameRet               `protobuf:"bytes,6,opt,name=GameRet" json:"GameRet,omitempty"`
	FinishedGroupUsers []int32                     `protobuf:"varint,7,rep,name=FinishedGroupUsers" json:"FinishedGroupUsers,omitempty"`
	UserBetInfo        *QZNN_UserBetInfo           `protobuf:"bytes,8,opt,name=UserBetInfo" json:"UserBetInfo,omitempty"`
}

func (x *QZNN_GameScene) Reset() {
	*x = QZNN_GameScene{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_GameScene) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_GameScene) ProtoMessage() {}

func (x *QZNN_GameScene) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_GameScene.ProtoReflect.Descriptor instead.
func (*QZNN_GameScene) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{11}
}

func (x *QZNN_GameScene) GetGameStep() int32 {
	if x != nil && x.GameStep != nil {
		return *x.GameStep
	}
	return 0
}

func (x *QZNN_GameScene) GetUserPoker() *UserPoker {
	if x != nil {
		return x.UserPoker
	}
	return nil
}

func (x *QZNN_GameScene) GetZhuangInfo() *QZNN_ConfirmZhuang {
	if x != nil {
		return x.ZhuangInfo
	}
	return nil
}

func (x *QZNN_GameScene) GetXianInfo() *QZNN_NotifyXianJiaBetTimes {
	if x != nil {
		return x.XianInfo
	}
	return nil
}

func (x *QZNN_GameScene) GetElapsedSeconds() int32 {
	if x != nil && x.ElapsedSeconds != nil {
		return *x.ElapsedSeconds
	}
	return 0
}

func (x *QZNN_GameScene) GetGameRet() *QZNN_GameRet {
	if x != nil {
		return x.GameRet
	}
	return nil
}

func (x *QZNN_GameScene) GetFinishedGroupUsers() []int32 {
	if x != nil {
		return x.FinishedGroupUsers
	}
	return nil
}

func (x *QZNN_GameScene) GetUserBetInfo() *QZNN_UserBetInfo {
	if x != nil {
		return x.UserBetInfo
	}
	return nil
}

type QZNN_NotifyUserGroupFinish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID *int32 `protobuf:"varint,1,opt,name=UserID" json:"UserID,omitempty"`
}

func (x *QZNN_NotifyUserGroupFinish) Reset() {
	*x = QZNN_NotifyUserGroupFinish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_NotifyUserGroupFinish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_NotifyUserGroupFinish) ProtoMessage() {}

func (x *QZNN_NotifyUserGroupFinish) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_NotifyUserGroupFinish.ProtoReflect.Descriptor instead.
func (*QZNN_NotifyUserGroupFinish) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{12}
}

func (x *QZNN_NotifyUserGroupFinish) GetUserID() int32 {
	if x != nil && x.UserID != nil {
		return *x.UserID
	}
	return 0
}

type QZNN_UserBetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ZhuangBetTimes []int32 `protobuf:"varint,1,rep,name=ZhuangBetTimes" json:"ZhuangBetTimes,omitempty"`
	XianBetTimes   []int64 `protobuf:"varint,2,rep,name=XianBetTimes" json:"XianBetTimes,omitempty"` //閒家押注倍數 or 金額範圍
}

func (x *QZNN_UserBetInfo) Reset() {
	*x = QZNN_UserBetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_UserBetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_UserBetInfo) ProtoMessage() {}

func (x *QZNN_UserBetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_UserBetInfo.ProtoReflect.Descriptor instead.
func (*QZNN_UserBetInfo) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{13}
}

func (x *QZNN_UserBetInfo) GetZhuangBetTimes() []int32 {
	if x != nil {
		return x.ZhuangBetTimes
	}
	return nil
}

func (x *QZNN_UserBetInfo) GetXianBetTimes() []int64 {
	if x != nil {
		return x.XianBetTimes
	}
	return nil
}

type QZNN_GameNoInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameNo *string `protobuf:"bytes,1,req,name=GameNo" json:"GameNo,omitempty"`
}

func (x *QZNN_GameNoInfo) Reset() {
	*x = QZNN_GameNoInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_GameNoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_GameNoInfo) ProtoMessage() {}

func (x *QZNN_GameNoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_GameNoInfo.ProtoReflect.Descriptor instead.
func (*QZNN_GameNoInfo) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{14}
}

func (x *QZNN_GameNoInfo) GetGameNo() string {
	if x != nil && x.GameNo != nil {
		return *x.GameNo
	}
	return ""
}

type QZNN_FinishPokerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserRet *QZNN_UserRet `protobuf:"bytes,1,req,name=UserRet" json:"UserRet,omitempty"`
}

func (x *QZNN_FinishPokerInfo) Reset() {
	*x = QZNN_FinishPokerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GameMsg_QZNN_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QZNN_FinishPokerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QZNN_FinishPokerInfo) ProtoMessage() {}

func (x *QZNN_FinishPokerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GameMsg_QZNN_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QZNN_FinishPokerInfo.ProtoReflect.Descriptor instead.
func (*QZNN_FinishPokerInfo) Descriptor() ([]byte, []int) {
	return file_GameMsg_QZNN_proto_rawDescGZIP(), []int{15}
}

func (x *QZNN_FinishPokerInfo) GetUserRet() *QZNN_UserRet {
	if x != nil {
		return x.UserRet
	}
	return nil
}

var File_GameMsg_QZNN_proto protoreflect.FileDescriptor

var file_GameMsg_QZNN_proto_rawDesc = []byte{
	0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x5f, 0x51, 0x5a, 0x4e, 0x4e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d,
	0x47, 0x61, 0x6d, 0x65, 0x4d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a,
	0x0d, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x65, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x53, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x04, 0x53, 0x74,
	0x65, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x28, 0x0a, 0x10, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x51,
	0x69, 0x61, 0x6e, 0x67, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x22, 0x82, 0x01, 0x0a, 0x12, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x12, 0x22, 0x0a, 0x0c, 0x5a, 0x68, 0x75, 0x61, 0x6e,
	0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x5a,
	0x68, 0x75, 0x61, 0x6e, 0x67, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x12, 0x32, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51,
	0x5a, 0x4e, 0x4e, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74, 0x52, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x65, 0x74, 0x73, 0x22, 0x5a, 0x0a, 0x0c, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x05, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65, 0x74,
	0x18, 0x03, 0x20, 0x02, 0x28, 0x08, 0x52, 0x09, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x65,
	0x74, 0x22, 0x2c, 0x0a, 0x14, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x58, 0x69, 0x61, 0x6e, 0x4a, 0x69,
	0x61, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x05, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22,
	0x50, 0x0a, 0x1a, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x58, 0x69,
	0x61, 0x6e, 0x4a, 0x69, 0x61, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x32, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x5a, 0x4e, 0x4e, 0x5f,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74,
	0x73, 0x22, 0x3d, 0x0a, 0x12, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x4c, 0x61, 0x73, 0x74, 0x50, 0x6f,
	0x6b, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x43, 0x61, 0x72, 0x64,
	0x22, 0x7a, 0x0a, 0x12, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72,
	0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x33, 0x0a, 0x0a, 0x43, 0x61, 0x72, 0x64, 0x73, 0x54,
	0x68, 0x72, 0x65, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x65, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x0a, 0x43, 0x61, 0x72, 0x64, 0x73, 0x54, 0x68, 0x72, 0x65, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x43,
	0x61, 0x72, 0x64, 0x73, 0x54, 0x77, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x08, 0x43, 0x61, 0x72, 0x64, 0x73, 0x54, 0x77, 0x6f, 0x22, 0x76, 0x0a, 0x0c,
	0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x74, 0x12, 0x34, 0x0a, 0x09,
	0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x5a, 0x4e, 0x4e, 0x5f,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x74, 0x52, 0x09, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x52,
	0x65, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51,
	0x5a, 0x4e, 0x4e, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x74, 0x52, 0x07, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x74, 0x22, 0x97, 0x02, 0x0a, 0x0c, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x57, 0x69, 0x6e, 0x4c, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x03, 0x52, 0x07,
	0x57, 0x69, 0x6e, 0x4c, 0x6f, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x69, 0x75, 0x4e, 0x69,
	0x75, 0x52, 0x65, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x4e, 0x69, 0x75, 0x4e,
	0x69, 0x75, 0x52, 0x65, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x4e, 0x69, 0x75, 0x4e, 0x69, 0x75, 0x52,
	0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0f,
	0x4e, 0x69, 0x75, 0x4e, 0x69, 0x75, 0x52, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x26, 0x0a, 0x0e, 0x4e, 0x69, 0x75, 0x4e, 0x69, 0x75, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0e, 0x4e, 0x69, 0x75, 0x4e, 0x69, 0x75, 0x42,
	0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x64, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x65, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x09, 0x43, 0x61, 0x72, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x4a, 0x61,
	0x63, 0x6b, 0x70, 0x6f, 0x74, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x4a, 0x61, 0x63, 0x6b, 0x70, 0x6f, 0x74, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x22, 0xd6,
	0x02, 0x0a, 0x10, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x12, 0x26, 0x0a, 0x0e, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x42, 0x65, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0e, 0x5a, 0x68, 0x75,
	0x61, 0x6e, 0x67, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x58,
	0x69, 0x61, 0x6e, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x0c, 0x58, 0x69, 0x61, 0x6e, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12,
	0x2e, 0x0a, 0x12, 0x51, 0x69, 0x61, 0x6e, 0x67, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x54, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x05, 0x52, 0x12, 0x51, 0x69, 0x61,
	0x6e, 0x67, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12,
	0x26, 0x0a, 0x0e, 0x58, 0x69, 0x61, 0x6e, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x18, 0x04, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0e, 0x58, 0x69, 0x61, 0x6e, 0x42, 0x65, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x61, 0x72, 0x64, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x02, 0x28,
	0x05, 0x52, 0x10, 0x43, 0x61, 0x72, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x06, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x42, 0x61, 0x73, 0x65, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x18, 0x07, 0x20, 0x02,
	0x28, 0x05, 0x52, 0x07, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x47,
	0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x08, 0x20, 0x02, 0x28, 0x05, 0x52, 0x06, 0x47, 0x61, 0x6d,
	0x65, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x79, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x18, 0x09, 0x20, 0x02, 0x28, 0x05, 0x52, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0xa7, 0x03, 0x0a, 0x0e, 0x51, 0x5a, 0x4e, 0x4e,
	0x5f, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x65, 0x70, 0x12, 0x31, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f,
	0x6b, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6e, 0x65, 0x74, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x09,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0a, 0x5a, 0x68, 0x75,
	0x61, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x52, 0x0a, 0x5a, 0x68, 0x75,
	0x61, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x40, 0x0a, 0x08, 0x58, 0x69, 0x61, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6e, 0x65, 0x74, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x58, 0x69, 0x61, 0x6e, 0x4a, 0x69, 0x61, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52,
	0x08, 0x58, 0x69, 0x61, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x45, 0x6c, 0x61,
	0x70, 0x73, 0x65, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0e, 0x45, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x12, 0x30, 0x0a, 0x07, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x5a,
	0x4e, 0x4e, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x74, 0x52, 0x07, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x55, 0x73, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x12, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x12, 0x3c, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x65, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x34, 0x0a, 0x1a, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x5e, 0x0a, 0x10, 0x51, 0x5a, 0x4e, 0x4e, 0x5f,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x5a,
	0x68, 0x75, 0x61, 0x6e, 0x67, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x0e, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x42, 0x65, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x58, 0x69, 0x61, 0x6e, 0x42, 0x65, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0c, 0x58, 0x69, 0x61, 0x6e, 0x42,
	0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x0f, 0x51, 0x5a, 0x4e, 0x4e, 0x5f,
	0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61,
	0x6d, 0x65, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65,
	0x4e, 0x6f, 0x22, 0x48, 0x0a, 0x14, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x46, 0x69, 0x6e, 0x69, 0x73,
	0x68, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x07, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x65,
	0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x74, 0x52, 0x07, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x74, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_GameMsg_QZNN_proto_rawDescOnce sync.Once
	file_GameMsg_QZNN_proto_rawDescData = file_GameMsg_QZNN_proto_rawDesc
)

func file_GameMsg_QZNN_proto_rawDescGZIP() []byte {
	file_GameMsg_QZNN_proto_rawDescOnce.Do(func() {
		file_GameMsg_QZNN_proto_rawDescData = protoimpl.X.CompressGZIP(file_GameMsg_QZNN_proto_rawDescData)
	})
	return file_GameMsg_QZNN_proto_rawDescData
}

var file_GameMsg_QZNN_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_GameMsg_QZNN_proto_goTypes = []interface{}{
	(*QZNN_GameStep)(nil),              // 0: netproto.QZNN_GameStep
	(*QZNN_QiangZhuang)(nil),           // 1: netproto.QZNN_QiangZhuang
	(*QZNN_ConfirmZhuang)(nil),         // 2: netproto.QZNN_ConfirmZhuang
	(*QZNN_UserBet)(nil),               // 3: netproto.QZNN_UserBet
	(*QZNN_XianJiaBetTimes)(nil),       // 4: netproto.QZNN_XianJiaBetTimes
	(*QZNN_NotifyXianJiaBetTimes)(nil), // 5: netproto.QZNN_NotifyXianJiaBetTimes
	(*QZNN_LastPokerCard)(nil),         // 6: netproto.QZNN_LastPokerCard
	(*QZNN_UserCardGroup)(nil),         // 7: netproto.QZNN_UserCardGroup
	(*QZNN_GameRet)(nil),               // 8: netproto.QZNN_GameRet
	(*QZNN_UserRet)(nil),               // 9: netproto.QZNN_UserRet
	(*QZNN_GameSetting)(nil),           // 10: netproto.QZNN_GameSetting
	(*QZNN_GameScene)(nil),             // 11: netproto.QZNN_GameScene
	(*QZNN_NotifyUserGroupFinish)(nil), // 12: netproto.QZNN_NotifyUserGroupFinish
	(*QZNN_UserBetInfo)(nil),           // 13: netproto.QZNN_UserBetInfo
	(*QZNN_GameNoInfo)(nil),            // 14: netproto.QZNN_GameNoInfo
	(*QZNN_FinishPokerInfo)(nil),       // 15: netproto.QZNN_FinishPokerInfo
	(*PokerCard)(nil),                  // 16: netproto.PokerCard
	(*GameUser)(nil),                   // 17: netproto.GameUser
	(*UserPoker)(nil),                  // 18: netproto.UserPoker
}
var file_GameMsg_QZNN_proto_depIdxs = []int32{
	3,  // 0: netproto.QZNN_ConfirmZhuang.UserBets:type_name -> netproto.QZNN_UserBet
	3,  // 1: netproto.QZNN_NotifyXianJiaBetTimes.UserBets:type_name -> netproto.QZNN_UserBet
	16, // 2: netproto.QZNN_LastPokerCard.Card:type_name -> netproto.PokerCard
	16, // 3: netproto.QZNN_UserCardGroup.CardsThree:type_name -> netproto.PokerCard
	16, // 4: netproto.QZNN_UserCardGroup.CardsTwo:type_name -> netproto.PokerCard
	9,  // 5: netproto.QZNN_GameRet.ZhuangRet:type_name -> netproto.QZNN_UserRet
	9,  // 6: netproto.QZNN_GameRet.UserRet:type_name -> netproto.QZNN_UserRet
	17, // 7: netproto.QZNN_UserRet.User:type_name -> netproto.GameUser
	16, // 8: netproto.QZNN_UserRet.CardGroup:type_name -> netproto.PokerCard
	18, // 9: netproto.QZNN_GameScene.UserPoker:type_name -> netproto.UserPoker
	2,  // 10: netproto.QZNN_GameScene.ZhuangInfo:type_name -> netproto.QZNN_ConfirmZhuang
	5,  // 11: netproto.QZNN_GameScene.XianInfo:type_name -> netproto.QZNN_NotifyXianJiaBetTimes
	8,  // 12: netproto.QZNN_GameScene.GameRet:type_name -> netproto.QZNN_GameRet
	13, // 13: netproto.QZNN_GameScene.UserBetInfo:type_name -> netproto.QZNN_UserBetInfo
	9,  // 14: netproto.QZNN_FinishPokerInfo.UserRet:type_name -> netproto.QZNN_UserRet
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_GameMsg_QZNN_proto_init() }
func file_GameMsg_QZNN_proto_init() {
	if File_GameMsg_QZNN_proto != nil {
		return
	}
	file_GameMsg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GameMsg_QZNN_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_GameStep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_QiangZhuang); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_ConfirmZhuang); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_UserBet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_XianJiaBetTimes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_NotifyXianJiaBetTimes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_LastPokerCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_UserCardGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_GameRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_UserRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_GameSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_GameScene); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_NotifyUserGroupFinish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_UserBetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_GameNoInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GameMsg_QZNN_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QZNN_FinishPokerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GameMsg_QZNN_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GameMsg_QZNN_proto_goTypes,
		DependencyIndexes: file_GameMsg_QZNN_proto_depIdxs,
		MessageInfos:      file_GameMsg_QZNN_proto_msgTypes,
	}.Build()
	File_GameMsg_QZNN_proto = out.File
	file_GameMsg_QZNN_proto_rawDesc = nil
	file_GameMsg_QZNN_proto_goTypes = nil
	file_GameMsg_QZNN_proto_depIdxs = nil
}
