// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: Game_QZNN.proto

package netproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type QZNN_GameMessageClassID int32

const (
	QZNN_GameMessageClassID_QiangZhuangID           QZNN_GameMessageClassID = 10001
	QZNN_GameMessageClassID_NotifyQiangZhuangBetID  QZNN_GameMessageClassID = 10002
	QZNN_GameMessageClassID_XianjiaBetTimesID       QZNN_GameMessageClassID = 10003
	QZNN_GameMessageClassID_NotifyXianjiaBetID      QZNN_GameMessageClassID = 10004
	QZNN_GameMessageClassID_LastPokerCardID         QZNN_GameMessageClassID = 10005
	QZNN_GameMessageClassID_GameRetID               QZNN_GameMessageClassID = 10006
	QZNN_GameMessageClassID_GameStepID              QZNN_GameMessageClassID = 10007
	QZNN_GameMessageClassID_GameSettingID           QZNN_GameMessageClassID = 10008
	QZNN_GameMessageClassID_GameSceneID             QZNN_GameMessageClassID = 10009
	QZNN_GameMessageClassID_OnUserZhuangBetID       QZNN_GameMessageClassID = 10010
	QZNN_GameMessageClassID_OnUserXianBetID         QZNN_GameMessageClassID = 10011
	QZNN_GameMessageClassID_CardGroupFinishID       QZNN_GameMessageClassID = 10012
	QZNN_GameMessageClassID_NotifyUserGroupFinishID QZNN_GameMessageClassID = 10013
	QZNN_GameMessageClassID_UserBetInfoID           QZNN_GameMessageClassID = 10014
	QZNN_GameMessageClassID_QZNNGameNo              QZNN_GameMessageClassID = 10015
	QZNN_GameMessageClassID_QZNNFinishPoker         QZNN_GameMessageClassID = 10016
)

// Enum value maps for QZNN_GameMessageClassID.
var (
	QZNN_GameMessageClassID_name = map[int32]string{
		10001: "QiangZhuangID",
		10002: "NotifyQiangZhuangBetID",
		10003: "XianjiaBetTimesID",
		10004: "NotifyXianjiaBetID",
		10005: "LastPokerCardID",
		10006: "GameRetID",
		10007: "GameStepID",
		10008: "GameSettingID",
		10009: "GameSceneID",
		10010: "OnUserZhuangBetID",
		10011: "OnUserXianBetID",
		10012: "CardGroupFinishID",
		10013: "NotifyUserGroupFinishID",
		10014: "UserBetInfoID",
		10015: "QZNNGameNo",
		10016: "QZNNFinishPoker",
	}
	QZNN_GameMessageClassID_value = map[string]int32{
		"QiangZhuangID":           10001,
		"NotifyQiangZhuangBetID":  10002,
		"XianjiaBetTimesID":       10003,
		"NotifyXianjiaBetID":      10004,
		"LastPokerCardID":         10005,
		"GameRetID":               10006,
		"GameStepID":              10007,
		"GameSettingID":           10008,
		"GameSceneID":             10009,
		"OnUserZhuangBetID":       10010,
		"OnUserXianBetID":         10011,
		"CardGroupFinishID":       10012,
		"NotifyUserGroupFinishID": 10013,
		"UserBetInfoID":           10014,
		"QZNNGameNo":              10015,
		"QZNNFinishPoker":         10016,
	}
)

func (x QZNN_GameMessageClassID) Enum() *QZNN_GameMessageClassID {
	p := new(QZNN_GameMessageClassID)
	*p = x
	return p
}

func (x QZNN_GameMessageClassID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QZNN_GameMessageClassID) Descriptor() protoreflect.EnumDescriptor {
	return file_Game_QZNN_proto_enumTypes[0].Descriptor()
}

func (QZNN_GameMessageClassID) Type() protoreflect.EnumType {
	return &file_Game_QZNN_proto_enumTypes[0]
}

func (x QZNN_GameMessageClassID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *QZNN_GameMessageClassID) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = QZNN_GameMessageClassID(num)
	return nil
}

// Deprecated: Use QZNN_GameMessageClassID.Descriptor instead.
func (QZNN_GameMessageClassID) EnumDescriptor() ([]byte, []int) {
	return file_Game_QZNN_proto_rawDescGZIP(), []int{0}
}

var File_Game_QZNN_proto protoreflect.FileDescriptor

var file_Game_QZNN_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x47, 0x61, 0x6d, 0x65, 0x5f, 0x51, 0x5a, 0x4e, 0x4e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xf7, 0x02, 0x0a, 0x17,
	0x51, 0x5a, 0x4e, 0x4e, 0x5f, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x0d, 0x51, 0x69, 0x61, 0x6e, 0x67,
	0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x49, 0x44, 0x10, 0x91, 0x4e, 0x12, 0x1b, 0x0a, 0x16, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x51, 0x69, 0x61, 0x6e, 0x67, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67,
	0x42, 0x65, 0x74, 0x49, 0x44, 0x10, 0x92, 0x4e, 0x12, 0x16, 0x0a, 0x11, 0x58, 0x69, 0x61, 0x6e,
	0x6a, 0x69, 0x61, 0x42, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x49, 0x44, 0x10, 0x93, 0x4e,
	0x12, 0x17, 0x0a, 0x12, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x58, 0x69, 0x61, 0x6e, 0x6a, 0x69,
	0x61, 0x42, 0x65, 0x74, 0x49, 0x44, 0x10, 0x94, 0x4e, 0x12, 0x14, 0x0a, 0x0f, 0x4c, 0x61, 0x73,
	0x74, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x49, 0x44, 0x10, 0x95, 0x4e, 0x12,
	0x0e, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x74, 0x49, 0x44, 0x10, 0x96, 0x4e, 0x12,
	0x0f, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x65, 0x70, 0x49, 0x44, 0x10, 0x97, 0x4e,
	0x12, 0x12, 0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x49,
	0x44, 0x10, 0x98, 0x4e, 0x12, 0x10, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x63, 0x65, 0x6e,
	0x65, 0x49, 0x44, 0x10, 0x99, 0x4e, 0x12, 0x16, 0x0a, 0x11, 0x4f, 0x6e, 0x55, 0x73, 0x65, 0x72,
	0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x42, 0x65, 0x74, 0x49, 0x44, 0x10, 0x9a, 0x4e, 0x12, 0x14,
	0x0a, 0x0f, 0x4f, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x58, 0x69, 0x61, 0x6e, 0x42, 0x65, 0x74, 0x49,
	0x44, 0x10, 0x9b, 0x4e, 0x12, 0x16, 0x0a, 0x11, 0x43, 0x61, 0x72, 0x64, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x49, 0x44, 0x10, 0x9c, 0x4e, 0x12, 0x1c, 0x0a, 0x17,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x49, 0x44, 0x10, 0x9d, 0x4e, 0x12, 0x12, 0x0a, 0x0d, 0x55, 0x73,
	0x65, 0x72, 0x42, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x44, 0x10, 0x9e, 0x4e, 0x12, 0x0f,
	0x0a, 0x0a, 0x51, 0x5a, 0x4e, 0x4e, 0x47, 0x61, 0x6d, 0x65, 0x4e, 0x6f, 0x10, 0x9f, 0x4e, 0x12,
	0x14, 0x0a, 0x0f, 0x51, 0x5a, 0x4e, 0x4e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x50, 0x6f, 0x6b,
	0x65, 0x72, 0x10, 0xa0, 0x4e, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6e, 0x65, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f,
}

var (
	file_Game_QZNN_proto_rawDescOnce sync.Once
	file_Game_QZNN_proto_rawDescData = file_Game_QZNN_proto_rawDesc
)

func file_Game_QZNN_proto_rawDescGZIP() []byte {
	file_Game_QZNN_proto_rawDescOnce.Do(func() {
		file_Game_QZNN_proto_rawDescData = protoimpl.X.CompressGZIP(file_Game_QZNN_proto_rawDescData)
	})
	return file_Game_QZNN_proto_rawDescData
}

var file_Game_QZNN_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Game_QZNN_proto_goTypes = []interface{}{
	(QZNN_GameMessageClassID)(0), // 0: netproto.QZNN_GameMessageClassID
}
var file_Game_QZNN_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Game_QZNN_proto_init() }
func file_Game_QZNN_proto_init() {
	if File_Game_QZNN_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Game_QZNN_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Game_QZNN_proto_goTypes,
		DependencyIndexes: file_Game_QZNN_proto_depIdxs,
		EnumInfos:         file_Game_QZNN_proto_enumTypes,
	}.Build()
	File_Game_QZNN_proto = out.File
	file_Game_QZNN_proto_rawDesc = nil
	file_Game_QZNN_proto_goTypes = nil
	file_Game_QZNN_proto_depIdxs = nil
}
