// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: Game_BY.proto

package netproto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BY_GameMessageClassID int32

const (
	BY_GameMessageClassID_BYSettingID            BY_GameMessageClassID = 10001 // 设置相关保留位置S2C
	BY_GameMessageClassID_FrameC2SID             BY_GameMessageClassID = 10100 // 客户端帧数据
	BY_GameMessageClassID_FrameS2CID             BY_GameMessageClassID = 10500 // 帧数据
	BY_GameMessageClassID_UserRecoverRetID       BY_GameMessageClassID = 10501 // 断线重连
	BY_GameMessageClassID_RobotID                BY_GameMessageClassID = 10800 //机器人消息
	BY_GameMessageClassID_BYLeaveTip             BY_GameMessageClassID = 10900 //踢出房提示訊息
	BY_GameMessageClassID_BYNotifyFish           BY_GameMessageClassID = 10901 //公告獲得魚
	BY_GameMessageClassID_BYGameStartC2SID       BY_GameMessageClassID = 10902 //Client通知Server可以準備開始
	BY_GameMessageClassID_BYGameStartS2CID       BY_GameMessageClassID = 10903 //Server通知Client可以開始
	BY_GameMessageClassID_BYGameCompetitionEndID BY_GameMessageClassID = 10904 //比賽結束
)

// Enum value maps for BY_GameMessageClassID.
var (
	BY_GameMessageClassID_name = map[int32]string{
		10001: "BYSettingID",
		10100: "FrameC2SID",
		10500: "FrameS2CID",
		10501: "UserRecoverRetID",
		10800: "RobotID",
		10900: "BYLeaveTip",
		10901: "BYNotifyFish",
		10902: "BYGameStartC2SID",
		10903: "BYGameStartS2CID",
		10904: "BYGameCompetitionEndID",
	}
	BY_GameMessageClassID_value = map[string]int32{
		"BYSettingID":            10001,
		"FrameC2SID":             10100,
		"FrameS2CID":             10500,
		"UserRecoverRetID":       10501,
		"RobotID":                10800,
		"BYLeaveTip":             10900,
		"BYNotifyFish":           10901,
		"BYGameStartC2SID":       10902,
		"BYGameStartS2CID":       10903,
		"BYGameCompetitionEndID": 10904,
	}
)

func (x BY_GameMessageClassID) Enum() *BY_GameMessageClassID {
	p := new(BY_GameMessageClassID)
	*p = x
	return p
}

func (x BY_GameMessageClassID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BY_GameMessageClassID) Descriptor() protoreflect.EnumDescriptor {
	return file_Game_BY_proto_enumTypes[0].Descriptor()
}

func (BY_GameMessageClassID) Type() protoreflect.EnumType {
	return &file_Game_BY_proto_enumTypes[0]
}

func (x BY_GameMessageClassID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BY_GameMessageClassID) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BY_GameMessageClassID(num)
	return nil
}

// Deprecated: Use BY_GameMessageClassID.Descriptor instead.
func (BY_GameMessageClassID) EnumDescriptor() ([]byte, []int) {
	return file_Game_BY_proto_rawDescGZIP(), []int{0}
}

var File_Game_BY_proto protoreflect.FileDescriptor

var file_Game_BY_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65, 0x5f, 0x42, 0x59, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0xdf, 0x01, 0x0a, 0x15, 0x42, 0x59,
	0x5f, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x0b, 0x42, 0x59, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x49, 0x44, 0x10, 0x91, 0x4e, 0x12, 0x0f, 0x0a, 0x0a, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x43, 0x32,
	0x53, 0x49, 0x44, 0x10, 0xf4, 0x4e, 0x12, 0x0f, 0x0a, 0x0a, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x53,
	0x32, 0x43, 0x49, 0x44, 0x10, 0x84, 0x52, 0x12, 0x15, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x52, 0x65, 0x74, 0x49, 0x44, 0x10, 0x85, 0x52, 0x12, 0x0c,
	0x0a, 0x07, 0x52, 0x6f, 0x62, 0x6f, 0x74, 0x49, 0x44, 0x10, 0xb0, 0x54, 0x12, 0x0f, 0x0a, 0x0a,
	0x42, 0x59, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x54, 0x69, 0x70, 0x10, 0x94, 0x55, 0x12, 0x11, 0x0a,
	0x0c, 0x42, 0x59, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x46, 0x69, 0x73, 0x68, 0x10, 0x95, 0x55,
	0x12, 0x15, 0x0a, 0x10, 0x42, 0x59, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43,
	0x32, 0x53, 0x49, 0x44, 0x10, 0x96, 0x55, 0x12, 0x15, 0x0a, 0x10, 0x42, 0x59, 0x47, 0x61, 0x6d,
	0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x32, 0x43, 0x49, 0x44, 0x10, 0x97, 0x55, 0x12, 0x1b,
	0x0a, 0x16, 0x42, 0x59, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x65, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x64, 0x49, 0x44, 0x10, 0x98, 0x55, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2f, 0x6e, 0x65, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_Game_BY_proto_rawDescOnce sync.Once
	file_Game_BY_proto_rawDescData = file_Game_BY_proto_rawDesc
)

func file_Game_BY_proto_rawDescGZIP() []byte {
	file_Game_BY_proto_rawDescOnce.Do(func() {
		file_Game_BY_proto_rawDescData = protoimpl.X.CompressGZIP(file_Game_BY_proto_rawDescData)
	})
	return file_Game_BY_proto_rawDescData
}

var file_Game_BY_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Game_BY_proto_goTypes = []interface{}{
	(BY_GameMessageClassID)(0), // 0: netproto.BY_GameMessageClassID
}
var file_Game_BY_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Game_BY_proto_init() }
func file_Game_BY_proto_init() {
	if File_Game_BY_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Game_BY_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Game_BY_proto_goTypes,
		DependencyIndexes: file_Game_BY_proto_depIdxs,
		EnumInfos:         file_Game_BY_proto_enumTypes,
	}.Build()
	File_Game_BY_proto = out.File
	file_Game_BY_proto_rawDesc = nil
	file_Game_BY_proto_goTypes = nil
	file_Game_BY_proto_depIdxs = nil
}
