games:
  - name: "BYDH"
    gameid: 38
    hallport: 5012
    roomtype: ['string1', 'string2', 'string3', 'string4', 'string5', 'string6']
  - name: "QZPN"
    gameid: 30
    hallport: 5014
    roomtype: ['string1', 'string2', 'string3', 'string4', 'string5', 'string6']